### ISSUE TITLE
mac 环境下无法编译成功Unrecognized option: 'emit'

### ISSUE THREAD

**Issue by xgs736214763** [SkyAPM/SkyAPM-php-sdk#510] opened 2022-07-27 09:16 UTC
php 7.4
SkyAPM-php-sdk-5.0.1
cmake 3.21.2
cargo 1.54.0
os 12,4
rustup 1.25.1 (bb60b1e89 2022-07-12)
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/22212275/181210677-f4faeb97-ee5b-4d13-a52f-1ef8250fa67b.png">

下面是编译信息

`➜  SkyAPM-php-sdk-5.0.1  sudo ./configure
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether cc accepts -g... yes
checking for cc option to enable C11 features... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin21.5.0
checking host system type... x86_64-apple-darwin21.5.0
checking target system type... x86_64-apple-darwin21.5.0
checking for PHP prefix... /Applications/MxSrvs/bin/php
checking for PHP includes... -I/Applications/MxSrvs/bin/php/include/php -I/Applications/MxSrvs/bin/php/include/php/main -I/Applications/MxSrvs/bin/php/include/php/TSRM -I/Applications/MxSrvs/bin/php/include/php/Zend -I/Applications/MxSrvs/bin/php/include/php/ext -I/Applications/MxSrvs/bin/php/include/php/ext/date/lib
checking for PHP extension directory... /Applications/MxSrvs/bin/php/lib/php/extensions/no-debug-non-zts-20190902
checking for PHP installed headers prefix... /Applications/MxSrvs/bin/php/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable skywalking support... yes, shared
checking for cargo... /Users/xiegaosheng/.cargo/bin/cargo
checking for rustfmt... /Users/xiegaosheng/.cargo/bin/rustfmt
checking for a sed that does not truncate output... /usr/bin/sed
checking for ld used by cc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 786432
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking if cc supports -fno-rtti -fno-exceptions... yes
checking for cc option to produce PIC... -fno-common
checking if cc PIC flag -fno-common works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin21.5.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
config.status: config.h is unchanged`

make 信息
` sudo make
cargo build --release --manifest-path=./Cargo.toml
   Compiling SkyAPM-php-sdk v1.0.0 (/usr/local/src/SkyAPM-php-sdk-5.0.1)
error: failed to run custom build command for `SkyAPM-php-sdk v1.0.0 (/usr/local/src/SkyAPM-php-sdk-5.0.1)`

Caused by:
  process didn't exit successfully: `/usr/local/src/SkyAPM-php-sdk-5.0.1/target/release/build/SkyAPM-php-sdk-1089a891fe5870cd/build-script-build` (exit status: 1)
  --- stdout
  Unrecognized option: 'emit'

  usage: rustfmt [options] <file>...

  Options:
      -h, --help          show this message
      -V, --version       show version information
      -v, --verbose       print verbose output
      -f, --force         force rustfmt to actually run
          --write-mode [replace|overwrite|display|diff|coverage|checkstyle]
                          mode to write in (not usable when piping from stdin)
          --skip-children
                          don't reformat child modules
          --config-help   show details of rustfmt configuration options
          --dump-default-config PATH
                          Dumps the default configuration to a file and exits.
          --dump-minimal-config PATH
                          Dumps configuration options that were checked during
                          formatting to a file.
          --config-path [Path for the configuration file]
                          Recursively searches the given path for the
                          rustfmt.toml config file. If not found reverts to the
                          input file path
          --file-lines JSON
                          Format specified line ranges. See README for more
                          detail on the JSON format.

make: *** [target/release/libsky_core_report.a] Error 101`

**Comment by xgs736214763** [comment] 2022-07-28 03:07
make error

**Comment by heyanlong** [comment] 2022-07-28 07:58
@jmjoy

**Comment by jmjoy** [comment] 2022-07-28 09:11
Mac and Linux are very different, does [SkyAPM-php-sdk](https://github.com/SkyAPM/SkyAPM-php-sdk) have plans to support Mac?

**Comment by jmjoy** [comment] 2022-07-28 13:06
Duplicate of #508

**Comment by heyanlong** [comment] 2022-07-29 02:50
Support from the beginning of the project.

**Comment by jmjoy** [comment] 2022-07-29 03:17
I'm not familiar with mac (and haven't used Apple devices), and should `macos-latest` support be added to CI?

**Comment by heyanlong** [comment] 2022-07-29 09:32
Yes, but not required, the problem is not system related.
Duplicate #508, Close this issue.

**Closed by heyanlong** 2022-07-29 09:32 UTC
